import type { Metadata } from 'next';
import Link from 'next/link';
import { buildMetadata, jsonLdBreadcrumb, siteConfig } from '@/lib/seo';

export const metadata: Metadata = buildMetadata({
  title: 'Terms of Service',
  description:
    'Terms of service for CronWizard — the free online cron expression generator and validator. Read our terms before using the Service.',
  path: '/terms',
  keywords: ['terms of service', 'cronwizard terms'],
});

export default function TermsPage() {
  const breadcrumb = jsonLdBreadcrumb([
    { name: 'Home', url: siteConfig.url },
    { name: 'Terms of Service', url: `${siteConfig.url}/terms` },
  ]);

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }}
      />
      <article className="max-w-3xl mx-auto w-full prose dark:prose-invert prose-headings:font-headline prose-headings:text-on-surface prose-p:text-on-surface-variant prose-li:text-on-surface-variant prose-strong:text-on-surface prose-a:text-primary">
        <h1 className="font-headline text-3xl font-bold tracking-tight text-on-surface mb-2">
          Terms of Service
        </h1>
        <p className="text-on-surface-variant/70 text-sm">Last updated: April 14, 2026</p>

        <h2 className="text-xl font-bold text-on-surface mt-10">1. Acceptance of Terms</h2>
        <p>
          By accessing or using CronWizard (the &quot;Service&quot;), you agree to be bound by
          these Terms of Service (&quot;Terms&quot;). If you do not agree with any part of these
          Terms, please discontinue use of the Service.
        </p>

        <h2 className="text-xl font-bold text-on-surface mt-10">2. Description of Service</h2>
        <p>
          CronWizard is a free online tool that helps developers generate, validate, and explain
          cron expressions. It supports Unix and Quartz formats, calculates next run times, and
          exports schedules to various platforms including Kubernetes, GitHub Actions, and
          systemd. All cron expression processing happens in your browser.
        </p>

        <h2 className="text-xl font-bold text-on-surface mt-10">3. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Use the Service for any unlawful purpose or in violation of any applicable laws.</li>
          <li>
            Attempt to disrupt, overload, or impair the Service, its servers, or connected
            networks.
          </li>
          <li>
            Reverse engineer, decompile, or attempt to extract source code beyond what is publicly
            available in our open-source repository.
          </li>
          <li>Use automated scripts to scrape or harvest content from the Service.</li>
          <li>
            Circumvent or interfere with the advertisements displayed on the Service, or click on
            advertisements in a fraudulent manner.
          </li>
        </ul>

        <h2 className="text-xl font-bold text-on-surface mt-10">
          4. Intellectual Property
        </h2>
        <p>
          The CronWizard name, logo, and website design are the property of CronWizard. The
          underlying source code is made available under an open-source license via our{' '}
          <a
            href="https://github.com/musanmaz/cronwizard"
            target="_blank"
            rel="noopener noreferrer"
          >
            GitHub repository
          </a>
          . Cron expressions you generate using the Service belong to you.
        </p>

        <h2 className="text-xl font-bold text-on-surface mt-10">
          5. No Warranty &amp; Disclaimer
        </h2>
        <p>
          The Service is provided &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; without warranties
          of any kind, either express or implied. CronWizard does not warrant that the Service
          will be uninterrupted, timely, secure, error-free, or that cron expressions generated by
          the Service will produce the exact behavior you expect on every target platform.
        </p>
        <p>
          <strong>
            Always verify generated schedules on your target system before relying on them in
            production. CronWizard is not liable for data loss, downtime, missed jobs, or any
            other damages resulting from schedules created using the Service.
          </strong>
        </p>

        <h2 className="text-xl font-bold text-on-surface mt-10">6. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by applicable law, in no event shall CronWizard, its
          maintainers, or contributors be liable for any indirect, incidental, special,
          consequential, or punitive damages arising out of your use of the Service.
        </p>

        <h2 className="text-xl font-bold text-on-surface mt-10">7. Third-Party Services</h2>
        <p>
          The Service uses third-party services such as Vercel (hosting &amp; analytics) and
          Google AdSense (advertising). Your use of the Service is also subject to those
          providers&apos; terms and privacy policies. See our{' '}
          <Link href="/privacy">Privacy Policy</Link> for details.
        </p>

        <h2 className="text-xl font-bold text-on-surface mt-10">8. Changes to the Terms</h2>
        <p>
          We may update these Terms from time to time. Continued use of the Service after an
          update constitutes acceptance of the revised Terms.
        </p>

        <h2 className="text-xl font-bold text-on-surface mt-10">9. Governing Law</h2>
        <p>
          These Terms are governed by general principles of international law and, where
          applicable, the laws of the jurisdiction in which CronWizard operates. Any disputes
          should first be raised via our contact channels before any legal action.
        </p>

        <h2 className="text-xl font-bold text-on-surface mt-10">10. Contact</h2>
        <p>
          If you have questions about these Terms, please visit our{' '}
          <Link href="/contact">contact page</Link>.
        </p>
      </article>
    </>
  );
}
