import type { ExportOptions, ExportTarget } from './types';

export function generateExport(
  cron: string,
  target: ExportTarget,
  options: ExportOptions = {},
): string {
  switch (target) {
    case 'k8s':
      return generateK8s(cron, options);
    case 'gha':
      return generateGha(cron, options);
    case 'systemd':
      return generateSystemd(cron, options);
    case 'docker':
      return generateDocker(cron, options);
    case 'terraform':
      return generateTerraform(cron, options);
    case 'crontab':
      return generateCrontab(cron, options);
    case 'launchd':
      return generateLaunchd(cron, options);
  }
}

function generateK8s(cron: string, opts: ExportOptions): string {
  const name = opts.name || 'my-cronjob';
  const image = opts.image || 'busybox:latest';
  const command = opts.command || 'echo "Hello from CronWizard"';

  return `apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${name}
spec:
  schedule: "${cron}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ${name}
              image: ${image}
              command:
                - /bin/sh
                - -c
                - ${command}
          restartPolicy: OnFailure`;
}

function generateGha(cron: string, opts: ExportOptions): string {
  const name = opts.name || 'scheduled-job';
  return `name: ${name}

on:
  schedule:
    - cron: '${cron}'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run task
        run: ${opts.command || 'echo "Hello from CronWizard"'}`;
}

function generateSystemd(cron: string, opts: ExportOptions): string {
  const name = opts.name || 'my-task';
  const desc = opts.description || 'Scheduled task generated by CronWizard';
  const command = opts.command || '/usr/local/bin/my-script.sh';
  const calendar = cronToSystemdCalendar(cron);

  return `# ${name}.service
[Unit]
Description=${desc}

[Service]
Type=oneshot
ExecStart=${command}

# ${name}.timer
[Unit]
Description=${desc} (timer)

[Timer]
OnCalendar=${calendar}
Persistent=true

[Install]
WantedBy=timers.target`;
}

function generateDocker(cron: string, opts: ExportOptions): string {
  const name = opts.name || 'my-service';
  const image = opts.image || 'busybox:latest';
  const command = opts.command || 'echo "Hello from CronWizard"';

  return `version: "3.8"

services:
  ${name}:
    image: ${image}
    entrypoint: /bin/sh -c
    command: "${command}"
    restart: "no"
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.${name}.schedule: "${cron}"
      ofelia.job-exec.${name}.command: "${command}"

  scheduler:
    image: mcuadros/ofelia:latest
    depends_on:
      - ${name}
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro`;
}

function generateTerraform(cron: string, opts: ExportOptions): string {
  const name = opts.name || 'my-scheduled-rule';
  const desc = opts.description || 'Scheduled rule generated by CronWizard';

  return `resource "aws_cloudwatch_event_rule" "${name}" {
  name                = "${name}"
  description         = "${desc}"
  schedule_expression = "cron(${cron})"
  state               = "ENABLED"
}

resource "aws_cloudwatch_event_target" "${name}_target" {
  rule      = aws_cloudwatch_event_rule.${name}.name
  target_id = "${name}-target"
  arn       = "arn:aws:lambda:us-east-1:123456789012:function:my-function"
}

resource "aws_lambda_permission" "${name}_allow_eventbridge" {
  statement_id  = "AllowExecutionFromEventBridge"
  action        = "lambda:InvokeFunction"
  function_name = "my-function"
  principal     = "events.amazonaws.com"
  source_arn    = aws_cloudwatch_event_rule.${name}.arn
}`;
}

function generateCrontab(cron: string, opts: ExportOptions): string {
  const desc = opts.description || 'Scheduled task generated by CronWizard';
  const command = opts.command || '/usr/local/bin/my-script.sh';

  return `# ${desc}
# Generated by CronWizard — https://cronwizard.com
${cron} ${command}`;
}

function generateLaunchd(cron: string, opts: ExportOptions): string {
  const name = opts.name || 'com.cronwizard.task';
  const command = opts.command || '/usr/local/bin/my-script.sh';
  const parts = cron.trim().split(/\s+/);

  let calendarEntries = '';
  if (parts.length === 5) {
    const [minute, hour, dom, month, dow] = parts;
    const entries: string[] = [];
    if (month !== '*') entries.push(`      <key>Month</key>\n      <integer>${month}</integer>`);
    if (dom !== '*') entries.push(`      <key>Day</key>\n      <integer>${dom}</integer>`);
    if (dow !== '*') entries.push(`      <key>Weekday</key>\n      <integer>${dow}</integer>`);
    if (hour !== '*') entries.push(`      <key>Hour</key>\n      <integer>${hour}</integer>`);
    if (minute !== '*') entries.push(`      <key>Minute</key>\n      <integer>${minute}</integer>`);
    calendarEntries = entries.join('\n');
  }

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${name}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${command}</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict>
${calendarEntries}
  </dict>
  <key>StandardOutPath</key>
  <string>/tmp/${name}.log</string>
  <key>StandardErrorPath</key>
  <string>/tmp/${name}.err</string>
</dict>
</plist>`;
}

function cronToSystemdCalendar(cron: string): string {
  const parts = cron.trim().split(/\s+/);
  if (parts.length !== 5) return cron;

  const [minute, hour, dom, month, dow] = parts;

  const dowMap: Record<string, string> = {
    '0': 'Sun', '1': 'Mon', '2': 'Tue', '3': 'Wed',
    '4': 'Thu', '5': 'Fri', '6': 'Sat', '7': 'Sun',
  };

  let daySpec = '';
  if (dow !== '*') {
    const days = dow.split(',').map((d) => {
      if (d.includes('-')) {
        const [start, end] = d.split('-');
        return `${dowMap[start] ?? start}..${dowMap[end] ?? end}`;
      }
      return dowMap[d] ?? d;
    });
    daySpec = days.join(',') + ' ';
  }

  const monthSpec = month === '*' ? '*' : month;
  const domSpec = dom === '*' ? '*' : dom;
  const hourSpec = hour === '*' ? '*' : hour.replace(',', '|');
  const minSpec = minute === '*' ? '*' : minute.replace(',', '|');

  if (minute.startsWith('*/') || hour.startsWith('*/')) {
    return `*-${monthSpec}-${domSpec} ${hourSpec}:${minSpec}:00`;
  }

  return `${daySpec}*-${monthSpec}-${domSpec} ${hourSpec}:${minSpec}:00`;
}
