import type { ExportOptions, ExportTarget } from './types';

export function generateExport(
  cron: string,
  target: ExportTarget,
  options: ExportOptions = {},
): string {
  switch (target) {
    case 'k8s':
      return generateK8s(cron, options);
    case 'gha':
      return generateGha(cron, options);
    case 'systemd':
      return generateSystemd(cron, options);
  }
}

function generateK8s(cron: string, opts: ExportOptions): string {
  const name = opts.name || 'my-cronjob';
  const image = opts.image || 'busybox:latest';
  const command = opts.command || 'echo "Hello from CronWizard"';

  return `apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${name}
spec:
  schedule: "${cron}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ${name}
              image: ${image}
              command:
                - /bin/sh
                - -c
                - ${command}
          restartPolicy: OnFailure`;
}

function generateGha(cron: string, opts: ExportOptions): string {
  const name = opts.name || 'scheduled-job';
  return `name: ${name}

on:
  schedule:
    - cron: '${cron}'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run task
        run: ${opts.command || 'echo "Hello from CronWizard"'}`;
}

function generateSystemd(cron: string, opts: ExportOptions): string {
  const name = opts.name || 'my-task';
  const desc = opts.description || 'Scheduled task generated by CronWizard';
  const command = opts.command || '/usr/local/bin/my-script.sh';
  const calendar = cronToSystemdCalendar(cron);

  return `# ${name}.service
[Unit]
Description=${desc}

[Service]
Type=oneshot
ExecStart=${command}

# ${name}.timer
[Unit]
Description=${desc} (timer)

[Timer]
OnCalendar=${calendar}
Persistent=true

[Install]
WantedBy=timers.target`;
}

function cronToSystemdCalendar(cron: string): string {
  const parts = cron.trim().split(/\s+/);
  if (parts.length !== 5) return cron;

  const [minute, hour, dom, month, dow] = parts;

  const dowMap: Record<string, string> = {
    '0': 'Sun', '1': 'Mon', '2': 'Tue', '3': 'Wed',
    '4': 'Thu', '5': 'Fri', '6': 'Sat', '7': 'Sun',
  };

  let daySpec = '';
  if (dow !== '*') {
    const days = dow.split(',').map((d) => {
      if (d.includes('-')) {
        const [start, end] = d.split('-');
        return `${dowMap[start] ?? start}..${dowMap[end] ?? end}`;
      }
      return dowMap[d] ?? d;
    });
    daySpec = days.join(',') + ' ';
  }

  const monthSpec = month === '*' ? '*' : month;
  const domSpec = dom === '*' ? '*' : dom;
  const hourSpec = hour === '*' ? '*' : hour.replace(',', '|');
  const minSpec = minute === '*' ? '*' : minute.replace(',', '|');

  if (minute.startsWith('*/') || hour.startsWith('*/')) {
    return `*-${monthSpec}-${domSpec} ${hourSpec}:${minSpec}:00`;
  }

  return `${daySpec}*-${monthSpec}-${domSpec} ${hourSpec}:${minSpec}:00`;
}
